<?php

namespace App\Tests\Entity;

use PHPUnit\Framework\TestCase;
use App\Entity\AddressBook;

class AddressBookTest extends TestCase
{
    private $addressBook;

    public function setUp()
    {
       // parent::setUp(); // TODO: Change the autogenerated stub
        $this->addressBook = new AddressBook();
    }

    public function tearDown()
    {
        // parent::tearDown(); // TODO: Change the autogenerated stub
        unset($this->addressBook);
    }

    public function testId()
    {
        $this->assertClassHasAttribute('id', 'App\Entity\AddressBook');
    }

    public function testFirstname()
    {
        $this->addressBook->setFirstname('Thomas');
        $this->assertEquals('Thomas', $this->addressBook->getFirstname());
        
    }
    

    public function testLastname()
    {
        $this->addressBook->setLastname('Basti');
        $this->assertEquals('Basti', $this->addressBook->getLastname());

    }


    public function testStreet()
    {
        $this->addressBook->setStreet('Brandeburg str');
        $this->assertEquals('Brandeburg str', $this->addressBook->getStreet());

    }


    public function testStreetnumber()
    {
        $this->addressBook->setStreetnumber('2009B');
        $this->assertEquals('2009B', $this->addressBook->getStreetnumber());
        
    }

    public function testZip()
    {
        $this->addressBook->setZip(10298);
        $this->assertEquals(10298, $this->addressBook->getZip());

    }

    public function testCity()
    {
        $this->addressBook->setCity('Berlin');
        $this->assertEquals('Berlin', $this->addressBook->getCity());

    }

    public function testCountry()
    {
        $this->addressBook->setCountry('Deutschland');
        $this->assertEquals('Deutschland', $this->addressBook->getCountry());

    }

    public function testPhonenumber()
    {
        $this->addressBook->setPhonenumber('+491290987654');
        $this->assertEquals('+491290987654', $this->addressBook->getPhonenumber());

    }


    public function testBirthday()
    {
        $this->addressBook->setBirthday('2000-12-20');
        $this->assertEquals('2000-12-20', $this->addressBook->getBirthday());

    }


    public function testEmail()
    {
        $this->addressBook->setEmail('bbb@yahoo.com');
        $this->assertEquals('bbb@yahoo.com', $this->addressBook->getEmail());

    }


    public function testPicture()
    {
        $this->addressBook->setPicture('234566.jpeg');
        $this->assertEquals('234566.jpeg', $this->addressBook->getPicture());

    }
    
}
