<?php

namespace App\Tests\Controller;


use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class AddressBookControllerTest extends WebTestCase
{
    private $client;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = static::createClient();

    }

    public function tearDown()
    {
        unset( $this->client );
    }

    /**
     * @dataProvider provideUrls
     */
    public function testShowAllAddress( $url )
    {

        $this->client->request('GET', $url);
        $this->assertTrue($this->client->getResponse()->isSuccessful() );
    }

    public function provideUrls(){
        return [
            ['/address/book/'],
            ['/address/book/new'],
            ['/address/book/2'],
            ['/address/book/2/edit'],

        ];
    }


}
